extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/recommended'
rules:
    '@typescript-eslint/no-explicit-any': 'off'
    '@typescript-eslint/no-unused-vars':
        - error
        - argsIgnorePattern: "^_"
